version: "3.8"

services:
#================================
#      POSTGRES
#================================
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./src/.env

#================================
#       WEB APPLICATION
#================================
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django_web
    restart: on-failure
    container_name: web
    env_file:
        - ./src/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./src:/src
      - web_media:/src/media
      - web_static:/src/static

#================================
#       NGINX
#================================
  nginx:
    image: nginx:1.21.6
    container_name: movies_nginx
    restart: always
    volumes:
      - web_static:/src/static
      - web_media:/src/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs/:/etc/nginx/conf.d:ro
    depends_on:
      - web
    ports:
      - "80:80"

volumes:
  db: {}
  web_media: {}
  web_static: {}